language: python
before_script: mkdir -p shippable/codecoverage shippable/testresults
python:
  - "2.7"
  - "3.3"
script:
  - ./manage test 
   - nosetests --with-xunit --xunit-file=shippable/testresults/
