#!/usr/bin/env python
# -*- coding: utf-8

import os
import sys


def main():
    try:
        cmd = sys.argv[1]
    except IndexError:
        sys.exit('manage takes at least one argument')
    if cmd == 'test':
        os.system('nosetests --with-coverage --cover-package=pywebstack')
    else:
        os.system('sudo PYTHONPATH={dir} bin/{cmd} {args}'.format(
            dir=os.path.dirname(__file__),
            cmd=cmd,
            args=' '.join(sys.argv[2:])
        ))


if __name__ == '__main__':
    main()
